### ISSUE TITLE
Build getting failed when trying to build DGPU driver image via KMM on Openshift 4.12

### ISSUE THREAD

**Issue by fayazahamedj** [intel/intel-technology-enabling-for-openshift#185]
Hello Team,

As we are not able to use the pre-build mode container image having a different kernel version than our kernel version i.e. 4.18.0-372.71.1.el8_6.x86_64, we are trying the On-premise Build Mode approach via KMM to build DGPU driver image in Openshift 4.12 as documented in below github link. 

[https://github.com/intel/intel-technology-enabling-for-openshift/tree/main/kmmo#managing-intel-dgpu-driver-with-kmm-operator]

Build is getting triggered, but unfortunately we are seeing below error(snippet below)

Also sharing the complete logs of the build pod for the analysis, require the team support take it up forward.
[intel-dgpu-on-premise-build-mode-r8hjv-undefined.log](https://github.com/intel/intel-technology-enabling-for-openshift/files/13646545/intel-dgpu-on-premise-build-mode-r8hjv-undefined.log)

Log snippet
```
/build/intel-gpu-i915-backports/drivers/gpu/drm/i915/fabric/netlink.c:1333:14: note: (near initialization for 'nl_iaf_cmds[19].start')
cc1: some warnings being treated as errors
make[6]: *** [scripts/Makefile.build:318: /build/intel-gpu-i915-backports/drivers/gpu/drm/i915/fabric/netlink.o] Error 1
make[5]: *** [scripts/Makefile.build:558: /build/intel-gpu-i915-backports/drivers/gpu/drm/i915/fabric] Error 2
make[4]: *** [scripts/Makefile.build:558: /build/intel-gpu-i915-backports/drivers/gpu/drm/i915] Error 2
make[3]: *** [Makefile:1584: _module_/build/intel-gpu-i915-backports] Error 2
make[2]: *** [Makefile.build:13: modules] Error 2
make[1]: *** [Makefile.real:105: modules] Error 2
make: *** [Makefile:50: modules] Error 2
error: build error: error building at STEP "RUN git clone -b ${I915_RELEASE} --single-branch https://github.com/intel-gpu/intel-gpu-i915-backports.git && cd intel-gpu-i915-backports && install -D COPYING /licenses/i915/COPYING && export LEX=flex; export YACC=bison && export OS_TYPE=rhel_9 && export OS_VERSION="9.2" && cp defconfigs/i915 .config && make olddefconfig && make modules -j $(nproc) && make modules_install": error while running runtime: exit status
```

**Comment by hershpa** [comment]
Hi @fayazahamedj, thanks for submitting the issue. The reason for that issue is that dockerfile recipe is for OpenShift 4.13 based on RHEL 9.2. OpenShift 4.12 is based on RHEL 8.6 and the dockerfile recipe to build driver container is different as a result.

Please use tag 1.0.1 release for OpenShift 4.12: https://github.com/intel/intel-technology-enabling-for-openshift/releases/tag/v1.0.1. Make sure to use the KMM module CR for the appropriate mode (pre-built or on-premise) from this tag.

For OCP 4.12 certified pre-built images, please refer to https://github.com/intel/intel-data-center-gpu-driver-for-openshift/tree/main/release#release-information

If you need to still use on premise build, please use tag 1.1.0 release dockerfile here: https://github.com/intel/intel-data-center-gpu-driver-for-openshift/blob/v1.1.0/docker/intel-dgpu-driver.Dockerfile

If anything is still unclear, feel free to comment again. Thanks!
